### ISSUE TITLE
Link to CAMELS data-set is broken due to the closing }

### ISSUE THREAD

**Issue by baccione** [kratzert/lstm_for_pub#1]
My browser resolves the link to the data-set as:
https://ral.ucar.edu/solutions/products/camels%7D

while it should be:
https://ral.ucar.edu/solutions/products/camels

the reason is the spelling of {https://ral.ucar.edu/solutions/products/camels} - the last '}' gets included in the URL (it happens the same right here too).

**Comment by kratzert** [comment]
Hi @baccione 
I don't know how I missed this issue. I am so sorry! Thanks for pointing me to the broken link, I just fixed it.

Sorry again,
Freddy
